package org.ljk.zodiac.cow.form.engine.model;

public class BizFirstMeta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.parent_code
     *
     * @mbggenerated
     */
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.c_name
     *
     * @mbggenerated
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.c_type
     *
     * @mbggenerated
     */
    private String cType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.length
     *
     * @mbggenerated
     */
    private Integer length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.is_null
     *
     * @mbggenerated
     */
    private Integer isNull;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.is_enable
     *
     * @mbggenerated
     */
    private Integer isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.is_query
     *
     * @mbggenerated
     */
    private Integer isQuery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.field_name
     *
     * @mbggenerated
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.field_type
     *
     * @mbggenerated
     */
    private String fieldType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.field_cn_name
     *
     * @mbggenerated
     */
    private String fieldCnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.source_type
     *
     * @mbggenerated
     */
    private Integer sourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.source_value
     *
     * @mbggenerated
     */
    private String sourceValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.view_json
     *
     * @mbggenerated
     */
    private String viewJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first_meta.valid_rule
     *
     * @mbggenerated
     */
    private String validRule;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first_meta
     *
     * @mbggenerated
     */
    public BizFirstMeta(Long id, String code, String parentCode, String cName, String cType, Integer length, Integer isNull, Integer isEnable, Integer isQuery, String fieldName, String fieldType, String fieldCnName, Integer sourceType, String sourceValue, String viewJson, String validRule) {
        this.id = id;
        this.code = code;
        this.parentCode = parentCode;
        this.cName = cName;
        this.cType = cType;
        this.length = length;
        this.isNull = isNull;
        this.isEnable = isEnable;
        this.isQuery = isQuery;
        this.fieldName = fieldName;
        this.fieldType = fieldType;
        this.fieldCnName = fieldCnName;
        this.sourceType = sourceType;
        this.sourceValue = sourceValue;
        this.viewJson = viewJson;
        this.validRule = validRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.id
     *
     * @return the value of biz_first_meta.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.code
     *
     * @return the value of biz_first_meta.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.parent_code
     *
     * @return the value of biz_first_meta.parent_code
     *
     * @mbggenerated
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.c_name
     *
     * @return the value of biz_first_meta.c_name
     *
     * @mbggenerated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.c_type
     *
     * @return the value of biz_first_meta.c_type
     *
     * @mbggenerated
     */
    public String getcType() {
        return cType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.length
     *
     * @return the value of biz_first_meta.length
     *
     * @mbggenerated
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.is_null
     *
     * @return the value of biz_first_meta.is_null
     *
     * @mbggenerated
     */
    public Integer getIsNull() {
        return isNull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.is_enable
     *
     * @return the value of biz_first_meta.is_enable
     *
     * @mbggenerated
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.is_query
     *
     * @return the value of biz_first_meta.is_query
     *
     * @mbggenerated
     */
    public Integer getIsQuery() {
        return isQuery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.field_name
     *
     * @return the value of biz_first_meta.field_name
     *
     * @mbggenerated
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.field_type
     *
     * @return the value of biz_first_meta.field_type
     *
     * @mbggenerated
     */
    public String getFieldType() {
        return fieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.field_cn_name
     *
     * @return the value of biz_first_meta.field_cn_name
     *
     * @mbggenerated
     */
    public String getFieldCnName() {
        return fieldCnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.source_type
     *
     * @return the value of biz_first_meta.source_type
     *
     * @mbggenerated
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.source_value
     *
     * @return the value of biz_first_meta.source_value
     *
     * @mbggenerated
     */
    public String getSourceValue() {
        return sourceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.view_json
     *
     * @return the value of biz_first_meta.view_json
     *
     * @mbggenerated
     */
    public String getViewJson() {
        return viewJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first_meta.valid_rule
     *
     * @return the value of biz_first_meta.valid_rule
     *
     * @mbggenerated
     */
    public String getValidRule() {
        return validRule;
    }
}