package org.ljk.zodiac.cow.form.engine.model;

public class BizFirst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first.a
     *
     * @mbggenerated
     */
    private String a;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first.b
     *
     * @mbggenerated
     */
    private String b;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first.c
     *
     * @mbggenerated
     */
    private String c;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first.d
     *
     * @mbggenerated
     */
    private String d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first.e
     *
     * @mbggenerated
     */
    private String e;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_first.f
     *
     * @mbggenerated
     */
    private String f;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first
     *
     * @mbggenerated
     */
    public BizFirst(Long id, String code, String a, String b, String c, String d, String e, String f) {
        this.id = id;
        this.code = code;
        this.a = a;
        this.b = b;
        this.c = c;
        this.d = d;
        this.e = e;
        this.f = f;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first.id
     *
     * @return the value of biz_first.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first.code
     *
     * @return the value of biz_first.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first.a
     *
     * @return the value of biz_first.a
     *
     * @mbggenerated
     */
    public String getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first.b
     *
     * @return the value of biz_first.b
     *
     * @mbggenerated
     */
    public String getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first.c
     *
     * @return the value of biz_first.c
     *
     * @mbggenerated
     */
    public String getC() {
        return c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first.d
     *
     * @return the value of biz_first.d
     *
     * @mbggenerated
     */
    public String getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first.e
     *
     * @return the value of biz_first.e
     *
     * @mbggenerated
     */
    public String getE() {
        return e;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_first.f
     *
     * @return the value of biz_first.f
     *
     * @mbggenerated
     */
    public String getF() {
        return f;
    }
}