package org.ljk.zodiac.cow.form.engine.model;

import java.util.ArrayList;
import java.util.List;

public class OrderMetaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    public OrderMetaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andColumnNameIsNull() {
            addCriterion("column_name is null");
            return (Criteria) this;
        }

        public Criteria andColumnNameIsNotNull() {
            addCriterion("column_name is not null");
            return (Criteria) this;
        }

        public Criteria andColumnNameEqualTo(String value) {
            addCriterion("column_name =", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotEqualTo(String value) {
            addCriterion("column_name <>", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameGreaterThan(String value) {
            addCriterion("column_name >", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameGreaterThanOrEqualTo(String value) {
            addCriterion("column_name >=", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameLessThan(String value) {
            addCriterion("column_name <", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameLessThanOrEqualTo(String value) {
            addCriterion("column_name <=", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameLike(String value) {
            addCriterion("column_name like", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotLike(String value) {
            addCriterion("column_name not like", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameIn(List<String> values) {
            addCriterion("column_name in", values, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotIn(List<String> values) {
            addCriterion("column_name not in", values, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameBetween(String value1, String value2) {
            addCriterion("column_name between", value1, value2, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotBetween(String value1, String value2) {
            addCriterion("column_name not between", value1, value2, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnTypeIsNull() {
            addCriterion("column_type is null");
            return (Criteria) this;
        }

        public Criteria andColumnTypeIsNotNull() {
            addCriterion("column_type is not null");
            return (Criteria) this;
        }

        public Criteria andColumnTypeEqualTo(String value) {
            addCriterion("column_type =", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeNotEqualTo(String value) {
            addCriterion("column_type <>", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeGreaterThan(String value) {
            addCriterion("column_type >", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeGreaterThanOrEqualTo(String value) {
            addCriterion("column_type >=", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeLessThan(String value) {
            addCriterion("column_type <", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeLessThanOrEqualTo(String value) {
            addCriterion("column_type <=", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeLike(String value) {
            addCriterion("column_type like", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeNotLike(String value) {
            addCriterion("column_type not like", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeIn(List<String> values) {
            addCriterion("column_type in", values, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeNotIn(List<String> values) {
            addCriterion("column_type not in", values, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeBetween(String value1, String value2) {
            addCriterion("column_type between", value1, value2, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeNotBetween(String value1, String value2) {
            addCriterion("column_type not between", value1, value2, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnLengthIsNull() {
            addCriterion("column_length is null");
            return (Criteria) this;
        }

        public Criteria andColumnLengthIsNotNull() {
            addCriterion("column_length is not null");
            return (Criteria) this;
        }

        public Criteria andColumnLengthEqualTo(Integer value) {
            addCriterion("column_length =", value, "columnLength");
            return (Criteria) this;
        }

        public Criteria andColumnLengthNotEqualTo(Integer value) {
            addCriterion("column_length <>", value, "columnLength");
            return (Criteria) this;
        }

        public Criteria andColumnLengthGreaterThan(Integer value) {
            addCriterion("column_length >", value, "columnLength");
            return (Criteria) this;
        }

        public Criteria andColumnLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("column_length >=", value, "columnLength");
            return (Criteria) this;
        }

        public Criteria andColumnLengthLessThan(Integer value) {
            addCriterion("column_length <", value, "columnLength");
            return (Criteria) this;
        }

        public Criteria andColumnLengthLessThanOrEqualTo(Integer value) {
            addCriterion("column_length <=", value, "columnLength");
            return (Criteria) this;
        }

        public Criteria andColumnLengthIn(List<Integer> values) {
            addCriterion("column_length in", values, "columnLength");
            return (Criteria) this;
        }

        public Criteria andColumnLengthNotIn(List<Integer> values) {
            addCriterion("column_length not in", values, "columnLength");
            return (Criteria) this;
        }

        public Criteria andColumnLengthBetween(Integer value1, Integer value2) {
            addCriterion("column_length between", value1, value2, "columnLength");
            return (Criteria) this;
        }

        public Criteria andColumnLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("column_length not between", value1, value2, "columnLength");
            return (Criteria) this;
        }

        public Criteria andColumnNullIsNull() {
            addCriterion("column_null is null");
            return (Criteria) this;
        }

        public Criteria andColumnNullIsNotNull() {
            addCriterion("column_null is not null");
            return (Criteria) this;
        }

        public Criteria andColumnNullEqualTo(Integer value) {
            addCriterion("column_null =", value, "columnNull");
            return (Criteria) this;
        }

        public Criteria andColumnNullNotEqualTo(Integer value) {
            addCriterion("column_null <>", value, "columnNull");
            return (Criteria) this;
        }

        public Criteria andColumnNullGreaterThan(Integer value) {
            addCriterion("column_null >", value, "columnNull");
            return (Criteria) this;
        }

        public Criteria andColumnNullGreaterThanOrEqualTo(Integer value) {
            addCriterion("column_null >=", value, "columnNull");
            return (Criteria) this;
        }

        public Criteria andColumnNullLessThan(Integer value) {
            addCriterion("column_null <", value, "columnNull");
            return (Criteria) this;
        }

        public Criteria andColumnNullLessThanOrEqualTo(Integer value) {
            addCriterion("column_null <=", value, "columnNull");
            return (Criteria) this;
        }

        public Criteria andColumnNullIn(List<Integer> values) {
            addCriterion("column_null in", values, "columnNull");
            return (Criteria) this;
        }

        public Criteria andColumnNullNotIn(List<Integer> values) {
            addCriterion("column_null not in", values, "columnNull");
            return (Criteria) this;
        }

        public Criteria andColumnNullBetween(Integer value1, Integer value2) {
            addCriterion("column_null between", value1, value2, "columnNull");
            return (Criteria) this;
        }

        public Criteria andColumnNullNotBetween(Integer value1, Integer value2) {
            addCriterion("column_null not between", value1, value2, "columnNull");
            return (Criteria) this;
        }

        public Criteria andColumnEnableIsNull() {
            addCriterion("column_enable is null");
            return (Criteria) this;
        }

        public Criteria andColumnEnableIsNotNull() {
            addCriterion("column_enable is not null");
            return (Criteria) this;
        }

        public Criteria andColumnEnableEqualTo(Integer value) {
            addCriterion("column_enable =", value, "columnEnable");
            return (Criteria) this;
        }

        public Criteria andColumnEnableNotEqualTo(Integer value) {
            addCriterion("column_enable <>", value, "columnEnable");
            return (Criteria) this;
        }

        public Criteria andColumnEnableGreaterThan(Integer value) {
            addCriterion("column_enable >", value, "columnEnable");
            return (Criteria) this;
        }

        public Criteria andColumnEnableGreaterThanOrEqualTo(Integer value) {
            addCriterion("column_enable >=", value, "columnEnable");
            return (Criteria) this;
        }

        public Criteria andColumnEnableLessThan(Integer value) {
            addCriterion("column_enable <", value, "columnEnable");
            return (Criteria) this;
        }

        public Criteria andColumnEnableLessThanOrEqualTo(Integer value) {
            addCriterion("column_enable <=", value, "columnEnable");
            return (Criteria) this;
        }

        public Criteria andColumnEnableIn(List<Integer> values) {
            addCriterion("column_enable in", values, "columnEnable");
            return (Criteria) this;
        }

        public Criteria andColumnEnableNotIn(List<Integer> values) {
            addCriterion("column_enable not in", values, "columnEnable");
            return (Criteria) this;
        }

        public Criteria andColumnEnableBetween(Integer value1, Integer value2) {
            addCriterion("column_enable between", value1, value2, "columnEnable");
            return (Criteria) this;
        }

        public Criteria andColumnEnableNotBetween(Integer value1, Integer value2) {
            addCriterion("column_enable not between", value1, value2, "columnEnable");
            return (Criteria) this;
        }

        public Criteria andFieldZhCnNameIsNull() {
            addCriterion("field_zh_cn_name is null");
            return (Criteria) this;
        }

        public Criteria andFieldZhCnNameIsNotNull() {
            addCriterion("field_zh_cn_name is not null");
            return (Criteria) this;
        }

        public Criteria andFieldZhCnNameEqualTo(String value) {
            addCriterion("field_zh_cn_name =", value, "fieldZhCnName");
            return (Criteria) this;
        }

        public Criteria andFieldZhCnNameNotEqualTo(String value) {
            addCriterion("field_zh_cn_name <>", value, "fieldZhCnName");
            return (Criteria) this;
        }

        public Criteria andFieldZhCnNameGreaterThan(String value) {
            addCriterion("field_zh_cn_name >", value, "fieldZhCnName");
            return (Criteria) this;
        }

        public Criteria andFieldZhCnNameGreaterThanOrEqualTo(String value) {
            addCriterion("field_zh_cn_name >=", value, "fieldZhCnName");
            return (Criteria) this;
        }

        public Criteria andFieldZhCnNameLessThan(String value) {
            addCriterion("field_zh_cn_name <", value, "fieldZhCnName");
            return (Criteria) this;
        }

        public Criteria andFieldZhCnNameLessThanOrEqualTo(String value) {
            addCriterion("field_zh_cn_name <=", value, "fieldZhCnName");
            return (Criteria) this;
        }

        public Criteria andFieldZhCnNameLike(String value) {
            addCriterion("field_zh_cn_name like", value, "fieldZhCnName");
            return (Criteria) this;
        }

        public Criteria andFieldZhCnNameNotLike(String value) {
            addCriterion("field_zh_cn_name not like", value, "fieldZhCnName");
            return (Criteria) this;
        }

        public Criteria andFieldZhCnNameIn(List<String> values) {
            addCriterion("field_zh_cn_name in", values, "fieldZhCnName");
            return (Criteria) this;
        }

        public Criteria andFieldZhCnNameNotIn(List<String> values) {
            addCriterion("field_zh_cn_name not in", values, "fieldZhCnName");
            return (Criteria) this;
        }

        public Criteria andFieldZhCnNameBetween(String value1, String value2) {
            addCriterion("field_zh_cn_name between", value1, value2, "fieldZhCnName");
            return (Criteria) this;
        }

        public Criteria andFieldZhCnNameNotBetween(String value1, String value2) {
            addCriterion("field_zh_cn_name not between", value1, value2, "fieldZhCnName");
            return (Criteria) this;
        }

        public Criteria andFieldEnUsNameIsNull() {
            addCriterion("field_en_us_name is null");
            return (Criteria) this;
        }

        public Criteria andFieldEnUsNameIsNotNull() {
            addCriterion("field_en_us_name is not null");
            return (Criteria) this;
        }

        public Criteria andFieldEnUsNameEqualTo(String value) {
            addCriterion("field_en_us_name =", value, "fieldEnUsName");
            return (Criteria) this;
        }

        public Criteria andFieldEnUsNameNotEqualTo(String value) {
            addCriterion("field_en_us_name <>", value, "fieldEnUsName");
            return (Criteria) this;
        }

        public Criteria andFieldEnUsNameGreaterThan(String value) {
            addCriterion("field_en_us_name >", value, "fieldEnUsName");
            return (Criteria) this;
        }

        public Criteria andFieldEnUsNameGreaterThanOrEqualTo(String value) {
            addCriterion("field_en_us_name >=", value, "fieldEnUsName");
            return (Criteria) this;
        }

        public Criteria andFieldEnUsNameLessThan(String value) {
            addCriterion("field_en_us_name <", value, "fieldEnUsName");
            return (Criteria) this;
        }

        public Criteria andFieldEnUsNameLessThanOrEqualTo(String value) {
            addCriterion("field_en_us_name <=", value, "fieldEnUsName");
            return (Criteria) this;
        }

        public Criteria andFieldEnUsNameLike(String value) {
            addCriterion("field_en_us_name like", value, "fieldEnUsName");
            return (Criteria) this;
        }

        public Criteria andFieldEnUsNameNotLike(String value) {
            addCriterion("field_en_us_name not like", value, "fieldEnUsName");
            return (Criteria) this;
        }

        public Criteria andFieldEnUsNameIn(List<String> values) {
            addCriterion("field_en_us_name in", values, "fieldEnUsName");
            return (Criteria) this;
        }

        public Criteria andFieldEnUsNameNotIn(List<String> values) {
            addCriterion("field_en_us_name not in", values, "fieldEnUsName");
            return (Criteria) this;
        }

        public Criteria andFieldEnUsNameBetween(String value1, String value2) {
            addCriterion("field_en_us_name between", value1, value2, "fieldEnUsName");
            return (Criteria) this;
        }

        public Criteria andFieldEnUsNameNotBetween(String value1, String value2) {
            addCriterion("field_en_us_name not between", value1, value2, "fieldEnUsName");
            return (Criteria) this;
        }

        public Criteria andColumnQueryEnableIsNull() {
            addCriterion("column_query_enable is null");
            return (Criteria) this;
        }

        public Criteria andColumnQueryEnableIsNotNull() {
            addCriterion("column_query_enable is not null");
            return (Criteria) this;
        }

        public Criteria andColumnQueryEnableEqualTo(Integer value) {
            addCriterion("column_query_enable =", value, "columnQueryEnable");
            return (Criteria) this;
        }

        public Criteria andColumnQueryEnableNotEqualTo(Integer value) {
            addCriterion("column_query_enable <>", value, "columnQueryEnable");
            return (Criteria) this;
        }

        public Criteria andColumnQueryEnableGreaterThan(Integer value) {
            addCriterion("column_query_enable >", value, "columnQueryEnable");
            return (Criteria) this;
        }

        public Criteria andColumnQueryEnableGreaterThanOrEqualTo(Integer value) {
            addCriterion("column_query_enable >=", value, "columnQueryEnable");
            return (Criteria) this;
        }

        public Criteria andColumnQueryEnableLessThan(Integer value) {
            addCriterion("column_query_enable <", value, "columnQueryEnable");
            return (Criteria) this;
        }

        public Criteria andColumnQueryEnableLessThanOrEqualTo(Integer value) {
            addCriterion("column_query_enable <=", value, "columnQueryEnable");
            return (Criteria) this;
        }

        public Criteria andColumnQueryEnableIn(List<Integer> values) {
            addCriterion("column_query_enable in", values, "columnQueryEnable");
            return (Criteria) this;
        }

        public Criteria andColumnQueryEnableNotIn(List<Integer> values) {
            addCriterion("column_query_enable not in", values, "columnQueryEnable");
            return (Criteria) this;
        }

        public Criteria andColumnQueryEnableBetween(Integer value1, Integer value2) {
            addCriterion("column_query_enable between", value1, value2, "columnQueryEnable");
            return (Criteria) this;
        }

        public Criteria andColumnQueryEnableNotBetween(Integer value1, Integer value2) {
            addCriterion("column_query_enable not between", value1, value2, "columnQueryEnable");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_meta
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}