package org.ljk.zodiac.cow.form.engine.model;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_amount
     *
     * @mbggenerated
     */
    private Double orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_address
     *
     * @mbggenerated
     */
    private String orderAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.commodity_no
     *
     * @mbggenerated
     */
    private String commodityNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.commoditf_quantity
     *
     * @mbggenerated
     */
    private Integer commoditfQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_date
     *
     * @mbggenerated
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_payer
     *
     * @mbggenerated
     */
    private String orderPayer;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    public Order(Long id, String orderNo, Double orderAmount, String orderAddress, String commodityNo, Integer commoditfQuantity, Date orderDate, String orderPayer) {
        this.id = id;
        this.orderNo = orderNo;
        this.orderAmount = orderAmount;
        this.orderAddress = orderAddress;
        this.commodityNo = commodityNo;
        this.commoditfQuantity = commoditfQuantity;
        this.orderDate = orderDate;
        this.orderPayer = orderPayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_no
     *
     * @return the value of order.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_amount
     *
     * @return the value of order.order_amount
     *
     * @mbggenerated
     */
    public Double getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_address
     *
     * @return the value of order.order_address
     *
     * @mbggenerated
     */
    public String getOrderAddress() {
        return orderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.commodity_no
     *
     * @return the value of order.commodity_no
     *
     * @mbggenerated
     */
    public String getCommodityNo() {
        return commodityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.commoditf_quantity
     *
     * @return the value of order.commoditf_quantity
     *
     * @mbggenerated
     */
    public Integer getCommoditfQuantity() {
        return commoditfQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_date
     *
     * @return the value of order.order_date
     *
     * @mbggenerated
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_payer
     *
     * @return the value of order.order_payer
     *
     * @mbggenerated
     */
    public String getOrderPayer() {
        return orderPayer;
    }
}