package org.ljk.zodiac.cow.form.engine.model;

public class OrderMeta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_meta.column_name
     *
     * @mbggenerated
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_meta.column_type
     *
     * @mbggenerated
     */
    private String columnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_meta.column_length
     *
     * @mbggenerated
     */
    private Integer columnLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_meta.column_null
     *
     * @mbggenerated
     */
    private Integer columnNull;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_meta.column_enable
     *
     * @mbggenerated
     */
    private Integer columnEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_meta.field_zh_cn_name
     *
     * @mbggenerated
     */
    private String fieldZhCnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_meta.field_en_us_name
     *
     * @mbggenerated
     */
    private String fieldEnUsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_meta.column_query_enable
     *
     * @mbggenerated
     */
    private Integer columnQueryEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    public OrderMeta(String columnName, String columnType, Integer columnLength, Integer columnNull, Integer columnEnable, String fieldZhCnName, String fieldEnUsName, Integer columnQueryEnable) {
        this.columnName = columnName;
        this.columnType = columnType;
        this.columnLength = columnLength;
        this.columnNull = columnNull;
        this.columnEnable = columnEnable;
        this.fieldZhCnName = fieldZhCnName;
        this.fieldEnUsName = fieldEnUsName;
        this.columnQueryEnable = columnQueryEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_meta.column_name
     *
     * @return the value of order_meta.column_name
     *
     * @mbggenerated
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_meta.column_type
     *
     * @return the value of order_meta.column_type
     *
     * @mbggenerated
     */
    public String getColumnType() {
        return columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_meta.column_length
     *
     * @return the value of order_meta.column_length
     *
     * @mbggenerated
     */
    public Integer getColumnLength() {
        return columnLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_meta.column_null
     *
     * @return the value of order_meta.column_null
     *
     * @mbggenerated
     */
    public Integer getColumnNull() {
        return columnNull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_meta.column_enable
     *
     * @return the value of order_meta.column_enable
     *
     * @mbggenerated
     */
    public Integer getColumnEnable() {
        return columnEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_meta.field_zh_cn_name
     *
     * @return the value of order_meta.field_zh_cn_name
     *
     * @mbggenerated
     */
    public String getFieldZhCnName() {
        return fieldZhCnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_meta.field_en_us_name
     *
     * @return the value of order_meta.field_en_us_name
     *
     * @mbggenerated
     */
    public String getFieldEnUsName() {
        return fieldEnUsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_meta.column_query_enable
     *
     * @return the value of order_meta.column_query_enable
     *
     * @mbggenerated
     */
    public Integer getColumnQueryEnable() {
        return columnQueryEnable;
    }
}