package org.ljk.zodiac.cow.form.engine.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.ljk.zodiac.cow.form.engine.model.BizFirstMeta;
import org.ljk.zodiac.cow.form.engine.model.BizFirstMetaExample;

public interface BizFirstMetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first_meta
     *
     * @mbggenerated
     */
    int countByExample(BizFirstMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first_meta
     *
     * @mbggenerated
     */
    int deleteByExample(BizFirstMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first_meta
     *
     * @mbggenerated
     */
    @Delete({
        "delete from biz_first_meta",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first_meta
     *
     * @mbggenerated
     */
    @Insert({
        "insert into biz_first_meta (id, code, ",
        "parent_code, c_name, ",
        "c_type, length, is_null, ",
        "is_enable, is_query, ",
        "field_name, field_type, ",
        "field_cn_name, source_type, ",
        "source_value, view_json, ",
        "valid_rule)",
        "values (#{id,jdbcType=BIGINT}, #{code,jdbcType=VARCHAR}, ",
        "#{parentCode,jdbcType=VARCHAR}, #{cName,jdbcType=VARCHAR}, ",
        "#{cType,jdbcType=VARCHAR}, #{length,jdbcType=INTEGER}, #{isNull,jdbcType=INTEGER}, ",
        "#{isEnable,jdbcType=INTEGER}, #{isQuery,jdbcType=INTEGER}, ",
        "#{fieldName,jdbcType=VARCHAR}, #{fieldType,jdbcType=VARCHAR}, ",
        "#{fieldCnName,jdbcType=VARCHAR}, #{sourceType,jdbcType=INTEGER}, ",
        "#{sourceValue,jdbcType=VARCHAR}, #{viewJson,jdbcType=VARCHAR}, ",
        "#{validRule,jdbcType=VARCHAR})"
    })
    int insert(BizFirstMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first_meta
     *
     * @mbggenerated
     */
    int insertSelective(BizFirstMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first_meta
     *
     * @mbggenerated
     */
    List<BizFirstMeta> selectByExample(BizFirstMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first_meta
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, code, parent_code, c_name, c_type, length, is_null, is_enable, is_query, ",
        "field_name, field_type, field_cn_name, source_type, source_value, view_json, ",
        "valid_rule",
        "from biz_first_meta",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    BizFirstMeta selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first_meta
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizFirstMeta record, @Param("example") BizFirstMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first_meta
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizFirstMeta record, @Param("example") BizFirstMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first_meta
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizFirstMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first_meta
     *
     * @mbggenerated
     */
    @Update({
        "update biz_first_meta",
        "set code = #{code,jdbcType=VARCHAR},",
          "parent_code = #{parentCode,jdbcType=VARCHAR},",
          "c_name = #{cName,jdbcType=VARCHAR},",
          "c_type = #{cType,jdbcType=VARCHAR},",
          "length = #{length,jdbcType=INTEGER},",
          "is_null = #{isNull,jdbcType=INTEGER},",
          "is_enable = #{isEnable,jdbcType=INTEGER},",
          "is_query = #{isQuery,jdbcType=INTEGER},",
          "field_name = #{fieldName,jdbcType=VARCHAR},",
          "field_type = #{fieldType,jdbcType=VARCHAR},",
          "field_cn_name = #{fieldCnName,jdbcType=VARCHAR},",
          "source_type = #{sourceType,jdbcType=INTEGER},",
          "source_value = #{sourceValue,jdbcType=VARCHAR},",
          "view_json = #{viewJson,jdbcType=VARCHAR},",
          "valid_rule = #{validRule,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BizFirstMeta record);
}