package org.ljk.zodiac.cow.form.engine.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.ljk.zodiac.cow.form.engine.model.BizFirst;
import org.ljk.zodiac.cow.form.engine.model.BizFirstExample;

public interface BizFirstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first
     *
     * @mbggenerated
     */
    int countByExample(BizFirstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first
     *
     * @mbggenerated
     */
    int deleteByExample(BizFirstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first
     *
     * @mbggenerated
     */
    @Delete({
        "delete from biz_first",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first
     *
     * @mbggenerated
     */
    @Insert({
        "insert into biz_first (id, code, ",
        "a, b, c, ",
        "d, e, f)",
        "values (#{id,jdbcType=BIGINT}, #{code,jdbcType=VARCHAR}, ",
        "#{a,jdbcType=VARCHAR}, #{b,jdbcType=VARCHAR}, #{c,jdbcType=VARCHAR}, ",
        "#{d,jdbcType=VARCHAR}, #{e,jdbcType=VARCHAR}, #{f,jdbcType=VARCHAR})"
    })
    int insert(BizFirst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first
     *
     * @mbggenerated
     */
    int insertSelective(BizFirst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first
     *
     * @mbggenerated
     */
    List<BizFirst> selectByExample(BizFirstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, code, a, b, c, d, e, f",
        "from biz_first",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    BizFirst selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizFirst record, @Param("example") BizFirstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizFirst record, @Param("example") BizFirstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizFirst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_first
     *
     * @mbggenerated
     */
    @Update({
        "update biz_first",
        "set code = #{code,jdbcType=VARCHAR},",
          "a = #{a,jdbcType=VARCHAR},",
          "b = #{b,jdbcType=VARCHAR},",
          "c = #{c,jdbcType=VARCHAR},",
          "d = #{d,jdbcType=VARCHAR},",
          "e = #{e,jdbcType=VARCHAR},",
          "f = #{f,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BizFirst record);
}