package org.ljk.zodiac.cow.form.engine.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.ljk.zodiac.cow.form.engine.model.OrderMeta;
import org.ljk.zodiac.cow.form.engine.model.OrderMetaExample;

public interface OrderMetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    int countByExample(OrderMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    int deleteByExample(OrderMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    @Insert({
        "insert into order_meta (column_name, column_type, ",
        "column_length, column_null, ",
        "column_enable, field_zh_cn_name, ",
        "field_en_us_name, column_query_enable)",
        "values (#{columnName,jdbcType=VARCHAR}, #{columnType,jdbcType=VARCHAR}, ",
        "#{columnLength,jdbcType=INTEGER}, #{columnNull,jdbcType=INTEGER}, ",
        "#{columnEnable,jdbcType=INTEGER}, #{fieldZhCnName,jdbcType=VARCHAR}, ",
        "#{fieldEnUsName,jdbcType=VARCHAR}, #{columnQueryEnable,jdbcType=INTEGER})"
    })
    int insert(OrderMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    int insertSelective(OrderMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    List<OrderMeta> selectByExample(OrderMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderMeta record, @Param("example") OrderMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_meta
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderMeta record, @Param("example") OrderMetaExample example);
}